apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/kustomization.yaml
  - prod-repo.yaml
  - cert-manager.yaml
  - cnpg.yaml
  - app-dev.yaml
  - app-prod.yaml
