apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: rd-automation
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: dev
    push:
      branch: dev
