resources:
  - namespace.yaml
  - ../../base
patches:
  - path: application.yaml
  - path: automation.yaml
  - path: ui-image.yaml
  - path: api-image.yaml
  - target:
      kind: Ingress
      name: rd-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.rd-capstone.local
      - op: replace
        path: /metadata/annotations/traefik.ingress.kubernetes.io/router.entrypoints
        value: websecure
  - target:
      kind: Certificate
      name: cert-manager
    patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: dev.rd-capstone.local
