resources:
  - namespace.yaml
  - ../../base
patches:
  - path: application.yaml
  - path: automation.yaml
  - path: uiImage.yaml
  - path: apiImage.yaml
  - target:
      kind: Ingress
      name: rd-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.rd-capstone.local
