{{- range $name, $app := .Values.rdApp }}
{{- if $app.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rd-app.fullname" $ }}-{{ $name }}
  labels:
    {{- include "rd-app.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ $app.replicas }}
  selector:
    matchLabels:
      {{- include "rd-app.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      name: {{ $name }}
      labels:
        {{- include "rd-app.labels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $app.image.repository }}:{{ $app.image.tag }}"
          {{- if $app.image.pullPolicy }}
          imagePullPolicy: {{ $app.image.pullPolicy }}
          {{- end }}
          ports:
            - containerPort: {{ $app.image.port }}
              protocol: TCP
          {{- if $app.probes.readiness }}
          readinessProbe:
            {{- toYaml $app.probes.readiness | nindent 12 }}
          {{- end }}
          {{- if $app.probes.liveness }}
          livenessProbe:
            {{- toYaml $app.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if $app.envFrom }}
          envFrom:
          {{- range $app.envFrom }}
            - {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if $app.env }}
          env:
          {{- range $app.env }}
            - {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if $app.restartPolicy }}
      restartPolicy: {{ $app.restartPolicy }}
      {{- end }}
{{- end }}
{{- end }}
