name: Build UI

on:
  push:
    branches: [ "dev", "prod" ]
    paths:
      - 'todo-ui/**'
  pull_request:
    branches: [ "dev", "prod" ]
    paths:
      - 'todo-ui/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      module: todo-ui
    secrets: inherit
