name: Build API

on:
  push:
    branches: [ "dev", "prod" ]
    paths:
      - 'todo-api/**'
  pull_request:
    branches: [ "dev", "prod" ]
    paths:
      - 'todo-api/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      module: todo-api
    secrets: inherit
