name: CI Template

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          architecture: x64
          java-version: '25'
          distribution: 'corretto'

      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Compute image tag
        id: tag
        run: echo "name=${{ steps.branch.outputs.name }}-$(date -u +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Build Docker with Maven
        run: mvn clean package -f ${{ inputs.module }} -Pdocker -Ddocker.image.tag=${{ steps.tag.outputs.name }}

      - name: Add extra tags
        run: |
          docker tag \
            "${{ vars.DOCKER_USERNAME }}/${{ inputs.module }}:${{ steps.tag.outputs.name }}" \
            "${{ vars.DOCKER_USERNAME }}/${{ inputs.module }}:${{ steps.branch.outputs.name }}"
          docker tag \
            "${{ vars.DOCKER_USERNAME }}/${{ inputs.module }}:${{ steps.tag.outputs.name }}" \
            "${{ vars.DOCKER_USERNAME }}/${{ inputs.module }}:latest"

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image ${{ steps.tag.outputs.name }}
        run: |
          docker push "${{ vars.DOCKER_USERNAME }}/${{ inputs.module }}:${{ steps.tag.outputs.name }}"
          docker push "${{ vars.DOCKER_USERNAME }}/${{ inputs.module }}:${{ steps.branch.outputs.name }}"
          docker push "${{ vars.DOCKER_USERNAME }}/${{ inputs.module }}:latest"
